function generatePrecacheItems() {
  // precache port big images for PWA
  return [
    { revision: null, url: 'favicon2.png' },
    { revision: null, url: 'data/ports.json' },
    { revision: null, url: 'data/skills_v4.json' },
    { revision: null, url: 'images/portfolio/azure_associate_s.jpg' },
    { revision: null, url: 'images/portfolio/azure_fundamentals_s.jpg' },
    { revision: null, url: 'images/portfolio/AWS_s.jpg' },
    { revision: null, url: 'images/portfolio/Python_s.jpg' },
    { revision: null, url: 'images/portfolio/Go_s.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_1s.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_2s.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_3s.jpg' },
    { revision: null, url: 'images/portfolio/pm_s.jpg' },
    { revision: null, url: 'images/portfolio/assertive_s.jpg' },
    { revision: null, url: 'images/portfolio/prodev_s.jpg' },
    { revision: null, url: 'images/portfolio/chairman_s.jpg' },
    { revision: null, url: 'images/portfolio/azure_associate.png' },
    { revision: null, url: 'images/portfolio/azure_fundamentals.png' },
    { revision: null, url: 'images/portfolio/AWS.jpg' },
    { revision: null, url: 'images/portfolio/Python.jpg' },
    { revision: null, url: 'images/portfolio/Go.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_1.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_2.jpg' },
    { revision: null, url: 'images/portfolio/Certificate_3.jpg' },
    { revision: null, url: 'images/portfolio/pm.jpg' },
    { revision: null, url: 'images/portfolio/assertive.jpg' },
    { revision: null, url: 'images/portfolio/prodev.jpg' },
    { revision: null, url: 'images/portfolio/chairman.jpg' },
    { revision: null, url: 'images/frontend/angular.png' },
    { revision: null, url: 'images/frontend/cypress.png' },
    { revision: null, url: 'images/frontend/selenium.png' },
    { revision: null, url: 'images/frontend/typeScript.png' },
    { revision: null, url: 'images/frontend/react.png' },
    { revision: null, url: 'images/frontend/pwa.png' },
    { revision: null, url: 'images/frontend/sass.png' },
    { revision: null, url: 'images/frontend/webpack.png' },
    { revision: null, url: 'images/frontend/less.jpg' },
    { revision: null, url: 'images/backend/cSharp.png' },
    { revision: null, url: 'images/backend/go.png' },
    { revision: null, url: 'images/backend/salesForce.png' },
    { revision: null, url: 'images/backend/ruby.png' },
    { revision: null, url: 'images/backend/python.png' },
    { revision: null, url: 'images/backend/node.png' },
    { revision: null, url: 'images/backend/graphql.png' },
    { revision: null, url: 'images/backend/specflow.png' },
    { revision: null, url: 'images/backend/grpc.png' },
    { revision: null, url: 'images/infrastructure/docker.png' },
    { revision: null, url: 'images/infrastructure/kubernetes.png' },
    { revision: null, url: 'images/infrastructure/oracleDatabase.jpg' },
    { revision: null, url: 'images/infrastructure/redis.png' },
    { revision: null, url: 'images/infrastructure/azure.png' },
    { revision: null, url: 'images/infrastructure/azure_keyvault.png' },
    { revision: null, url: 'images/infrastructure/aws.png' },
    { revision: null, url: 'images/infrastructure/sqlServer.jpg' },
    { revision: null, url: 'images/infrastructure/postgreSql.png' },
    { revision: null, url: 'images/infrastructure/rabbit_mq.png' },
    { revision: null, url: 'images/infrastructure/firebase.png' },
    { revision: null, url: 'images/tools/gitHub.png' },
    { revision: null, url: 'images/tools/jira.png' },
    { revision: null, url: 'images/tools/sqlDeveloper.png' },
    { revision: null, url: 'images/tools/sqlMgmt.jpg' },
    { revision: null, url: 'images/tools/teamCity.png' },
    { revision: null, url: 'images/tools/vs.png' },
    { revision: null, url: 'images/tools/vs_code.png' },
    { revision: null, url: 'images/tools/tableau.png' },
    { revision: null, url: 'images/tools/terraform.png' },
    { revision: null, url: 'images/tools/azure_devops.png' },
  ];
}

export default generatePrecacheItems;
